project:
  type: website
  output-dir: docs

website:
  title: "Taras Tsymbal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
  sidebar:
    style: "docked"
    contents:
      - section: "Research"
        contents:
          - authoritarianism.qmd
          - spatial_voting.qmd
          - market_integration.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

